apiVersion: apps/v1
kind: Deployment
metadata:
  name: many-pods
  namespace: default
spec:
  replicas: 50
  selector:
    matchLabels:
      app: many-pods
  template:
    metadata:
      labels:
        app: many-pods
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
